version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cms-app
    container_name: cms-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-cms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cm_user
      MYSQL_PASSWORD: cms_secret
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-cms
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata:
